### ISSUE TITLE
forked

### ISSUE THREAD

**Issue by timabell** [aidanlister/jquery-stickytabs#2]
Hey there, I see you've created a repo for this now. Would you like to take over what I'd done so far? https://github.com/timabell/jquery.stickytabs

There's also a nuget package that I published from it https://www.nuget.org/packages/jquery.stickytabs/

**Comment by aidanlister** [comment]
Hey timabell, would you like commit access or are there any changes that are just in your version?

**Comment by timabell** [comment]
I don't think I need commit access, but thanks. There's no changes to the code so my version can just die off.

You might want to grab the readme and modify it to suit as it's more extensive than what you currently have.

The only other thing is the nuget package. I don't know if that's of interest to you or if it's something you'd want to take ownership of. I could maintain that independently but base it on your repo instead of mine if that suits. I do ASP.NET contracting for a living so that's why the nuget package is of interest to me.

Oh and thanks for publishing this in the first place, very nice piece of work, and neatly solved a problem in my current project.

**Comment by aidanlister** [comment]
What do I need to do for the nuget thing? If you could maintain it that's fine .. do I just add your nuget file to my repo?

**Comment by timabell** [comment]
I think it probably only makes sense to put the nuget file in your repo if you're going to maintain the published nuget package. If not I'll keep the nuget elsewhere and track your repo.

To publish it I use a windows machine and the [nuget tool](http://docs.nuget.org/Create/Using-a-Gui-to-build-packages) you can download from their site, though it's not the only way of doing it.

So it looks like the best approach is for me to look after the nuget bit and just package whatever you publish here then. If you could tag releases that would be handy as then I'll know when it's stable enough to update the package rather than just tracking master.

**Comment by aidanlister** [comment]
Alright I have no interest in windows so I'll leave it to you :)
