### ISSUE TITLE
Tag a stable branch

### ISSUE THREAD

**Issue by holtkamp** [aidanlister/jquery-stickytabs#6]
Thanks for accepting, https://github.com/aidanlister/jquery-stickytabs/pull/4. 

It would be nice if you can tag the current master branch with a version number (1.2.0, or 1.3.0 because of new functionality in https://github.com/aidanlister/jquery-stickytabs/pull/3). 

This way projects to not need to refer to the development / master branch, which decreases the risk on breaking code :).

**Comment by aidanlister** [comment]
done
