### ISSUE TITLE
Keep path name on hashchange

### ISSUE THREAD

**Issue by althaus** [aidanlister/jquery-stickytabs#9]
Hey,

I'm playing around with your nifty plugin to streamline some Bootstrap Tabs. I encountered an issue with the pathname on switching the tabs:

When I'm on a page like

```
http://example.org/foo/bar/page
```

containing tabs `#foo` and `#bar` switching a tab causes the browser to show

```
http://example.org/#foo
http://example.org/#bar
```

which isn't what I'd want. Changing L26 [1] from

```
history.pushState(null, null, '#' + hash);
```

to 

```
history.pushState(null, null, window.location.pathname + '#' + hash);
```

fixes this for me and the browser shows the desired history updates:

```
http://example.org/foo/bar/page#foo
http://example.org/foo/bar/page#bar
```

Cheers
Matthias

[1] https://github.com/aidanlister/jquery-stickytabs/blob/master/jquery.stickytabs.js#L26

**Comment by aidanlister** [comment]
Thanks, I've pushed 6d05378, let me know if that fixes your issue and thanks for providing the fix!

**Comment by althaus** [comment]
6d05378 works fine for me.
